#!/usr/bin/env bash
# version.sh — writes release.json from version.txt + git. Idempotent; safe to run
# on every start. For this C++ app the compile-time version header is generated by
# CMake (from version.txt); release.json is the runtime build-provenance record the
# standard expects.

set -euo pipefail
cd "$(dirname "$0")/.."   # project root

VER=$(tr -d '[:space:]' < version.txt)

if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "nogit")
  if git diff --quiet HEAD 2>/dev/null && git diff --cached --quiet 2>/dev/null; then
    GIT_DIRTY="false"
  else
    GIT_DIRTY="true"
  fi
else
  GIT_SHA="nogit"
  GIT_DIRTY="unknown"
fi

BUILT_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

CXX_VER="none"
if command -v g++ >/dev/null 2>&1; then
  CXX_VER=$(g++ --version | head -1)
elif command -v clang++ >/dev/null 2>&1; then
  CXX_VER=$(clang++ --version | head -1)
fi

QT_VER="unknown"
if command -v qmake6 >/dev/null 2>&1; then
  QT_VER=$(qmake6 -query QT_VERSION 2>/dev/null || echo unknown)
elif command -v pkg-config >/dev/null 2>&1; then
  QT_VER=$(pkg-config --modversion Qt6Widgets 2>/dev/null || echo unknown)
fi

# Hash the source tree (collectors + ui) as a coarse build fingerprint.
SRC_SHA="none"
if command -v sha256sum >/dev/null 2>&1; then
  SRC_SHA=$(find src -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.in' \) -print0 \
            2>/dev/null | sort -z | xargs -0 sha256sum 2>/dev/null | sha256sum | cut -c1-12)
fi

cat > release.json <<EOF
{
  "version": "$VER",
  "git_sha": "$GIT_SHA",
  "git_dirty": $GIT_DIRTY,
  "built_at": "$BUILT_AT",
  "cxx": "$CXX_VER",
  "qt_version": "$QT_VER",
  "src_sha": "$SRC_SHA"
}
EOF

echo "release.json written:"
sed 's/^/  /' release.json
